### ISSUE TITLE
Support index styles

### ISSUE THREAD

**Issue by m4dz** [brunch/stylus-brunch#35]
Hi!

I'm working on a huge project with Stylus, and intensively use the [index styles import feature](https://learnboost.github.io/stylus/docs/import.html#stylus-import). Basically, you can have a file tree like:

```txt
- styles
  |- main.styl
  `- foo
    |- index.styl
    |- _bar.styl
    `- _baz.styl
```

with `foo/index.styl` containing:

```stylus
@import '_bar'
@import '_baz'
```

You then simply import the `foo` module in main style with:

```stylus
@import 'foo'
```

to get the `foo/index.styl` file imported.

It works well at first compile time, but then, when brunch runs in _watch_ mode, changes in any of the `foo/*` files is detected, but Brunch doesn't know where those files are imported as dependency, so the final CSS file isn't recompiled.

If you change the main import statement to `@import 'foo/index'`, then it works well.

Can we add support for the implicit _index import_ in the Brunch dependencies tree to get it working even in watch mode?

Thanks a lot!

**Comment by es128** [comment]
I just [opened an issue in progeny](https://github.com/es128/progeny/issues/10) for adding this feature to the dependency resolution.

PR welcome. It was done in a fork (and never PR'd) a long time ago that you could use for reference, but the implementation would have to be modified to not rely on synchronous file system calls.

**Comment by m4dz** [comment]
Just saw in brunch-stylus code where dependencies are loaded. I'm looking to do a PR to handle it in progeny, thanks @es128!
