### ISSUE TITLE
Variables not being recognized

### ISSUE THREAD

**Issue by igregson** [brunch/stylus-brunch#37]
Greetings,

Say I have this:

```
@require 'base/vars-default'
```

in my base `app.styl` file. 

Every file that is required/imported after that should have access to the variables defined in `vars-default.styl`, correct? This isn't currently working. 

I'm new to Brunch so could just be leaving off a configuration parameter or something. Do I need to specify any configuration for this to work? 

Stylus is compiling just fine currently, but the variables aren't converting to their values (they're simply being passed as their raw variable names).

**Comment by es128** [comment]
Not sure. This is a question for the stylus project.

**Comment by igregson** [comment]
Hmm... it's just that this has worked with every other method of compiling Stylus that I've used (command line, gulp, NPM, etc). That's why I opened the issue here and not directly on the main Stylus repo.

**Comment by es128** [comment]
I don't know. Do you use any special options with those other methods?

The stylus library handles the integration of imported files on its own, this plugin does not have an impact on that.

**Comment by es128** [comment]
I would guess the issue on your end may come down to something simple, like a typo

**Comment by igregson** [comment]
Stylus is compiling the files just fine, except for variables "not working." That's the strange thing.

**Comment by igregson** [comment]
I'll keep troubleshooting... thanks anyways.
