### ISSUE TITLE
Endless compiling

### ISSUE THREAD

**Issue by kana-sama** [brunch/stylus-brunch#53]
When I have `.styl` files in project, I get this:
```
> node -v
v7.2.0
> brunch build
(node:23284) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Path must be a string. Received undefined
(node:23284) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
29 Nov 01:56:17 - info: compiling
29 Nov 01:56:21 - info: compiling.
29 Nov 01:56:25 - info: compiling..
29 Nov 01:56:29 - info: compiling...
```

**Comment by denysdovhan** [comment]
Hi, can you, please, create a repo that reproduce this bug? I'll try fix this problem.

**Comment by kana-sama** [comment]
https://github.com/kana-sama/stylus_brunch_bug
It is blank `phoenix` project + `stylus-brunch`, but when I launch `brunch` independently, I get the same trouble.

**Comment by denysdovhan** [comment]
Yeah thank you. Gonna jump in sources and try to find the root of problem. Stay in touch.

**Comment by denysdovhan** [comment]
BTW, try to downgrade you node's version to 6 LTS. It may help.

**Comment by kana-sama** [comment]
downgrading removes deprecation warning, but all the rest is the same.

**Comment by denysdovhan** [comment]
@kana-sama did you downgraded to 6? Try to downgrade lower, if you can.

**Comment by shvaikalesh** [comment]
Hey @kana-sama, thanks for reaching out.

Please try with `"brunch": "^2"` in `package.json`.

**Comment by kana-sama** [comment]
@shvaikalesh it didn't help me
@denysdovhan node v5 didn't help too
```bash
$ cat package.json | grep stylus-brunch
    "stylus-brunch": "^2",
$ node -v
v5.12.0
$ brunch build
03 Dec 18:08:04 - info: compiling
03 Dec 18:08:08 - info: compiling.
03 Dec 18:08:12 - info: compiling..
03 Dec 18:08:16 - info: compiling...
03 Dec 18:08:20 - info: compiling
03 Dec 18:08:24 - info: compiling.
03 Dec 18:08:28 - info: compiling..
03 Dec 18:08:32 - info: still compiling...
```

**Comment by kana-sama** [comment]
> Please try with "brunch": "^2" in package.json (works for me in the provided repo).
Finally, it fixes my problem on other machine 🌚
`npm i --save-dev` with `"brunch": "^2"` on my machine updates to `2.8.0`, but on other machine (with node4) it updates to `2.9.1`
Thanks you.

**Comment by timnew** [comment]
I still suffer from this issue, is it fixed? Or I have to downgrade it ?!
I'm using `"stylus-brunch": "^2.10.0"`, `"brunch": "2.7.4"`, and `node v6.9.0`

**Comment by shvaikalesh** [comment]
@timnew Hey, try latest (`^2`) Brunch.

Generally, plugins with version `~2.x` are compatible only with Brunch `>=2.x`

**Comment by soundstruck** [comment]
I'm having this same issue. tried downgrading node, various node versions, no dice.
```
"devDependencies": {
    "babel-brunch": "~6.1.1",
    "babel-plugin-transform-runtime": "^6.23.0",
    "brunch": "^2.10.1",
    "vue-brunch": "^2.0.1",
    "clean-css-brunch": "^2.10.0",
    "stylus-brunch": "^2.10.0",
    "uglify-js-brunch": "^2.10.0"
  }
```
getting this error when running brunch build --production
```
brunch:pipeline Compiling web/static/css/main.styl @ StylusCompiler
brunch:pipeline Dependencies web/static/css/main.styl @ StylusCompiler
(node:6942) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Path must be a string. Received undefined
```

Any ideas what I'm doing wrong?
