### ISSUE TITLE
Plugins and config format

### ISSUE THREAD

**Issue by r3verser** [brunch/stylus-brunch#54]
Why on main website configs typed as js objects but here in another format
```
config =
  plugins:
    stylus:
      plugins: ['my-stylus-plugin']
```
instead of

```
  plugins: {
    stylus: {
      includeCss: true,
      plugins: ['my-stylus-plugin']
    }
  }
```
And second question, what do you mean - stylus plugins

> You can include Stylus plugins with a config directive config.plugins.stylus.plugins (array) with paths to require the needed plugins. You will have to include your plugin dependencies in package.json.

Where i can find those middleware plugins, and do i need to install them to get Stylus compiler features work as stated on the official Stylus page?
Thanks.

**Comment by denysdovhan** [comment]
**First question:**

> Why on main website configs typed as js objects but here in another format

Examples in this repo are written in [CoffeeScript](http://coffeescript.org) using [coffeescript object literals](http://coffeescript.org/#objects_and_arrays). For example:

```coffee
config =
  plugins:
    stylus:
      plugins: ['my-stylus-plugin']
```

Corresponds to this core written in JavaScript:

```js
var config = {
  plugins: {
    stylus: {
      plugins: ['my-stylus-plugin']
    }
  }
}
```

**Second question:**

> what do you mean - stylus plugins

Stylus gives us ability to use plugins and extension through [JavaScript API](http://stylus-lang.com/docs/js.html). Here are [useful gist about Stylus Plugin usage](https://gist.github.com/jescalan/8263065).

The most popular plugins for Stylus is [**nib**](https://github.com/tj/nib). You may find it useful in your development. You can install nib using npm:

```sh
$ npm install nib
```

Take a look in repo nib's for [usage examples](https://github.com/tj/nib#javascript-api).

> Where i can find those middleware plugins

Unfortunately, I don't know about any existing Stylus Plugin's registry. Maybe someone else can help you here.

> do i need to install them to get Stylus compiler features work as stated on the official Stylus page?

Yes, you need to install plugins through npm, but if you're going to use only Stylus' features, `stylus` package (or `stylus-brunch` in this case) is enough for you.

**Comment by r3verser** [comment]
@denysdovhan thank you for the comprehensive answer! :+1:
